# Generated by Django 3.2.3 on 2021-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parea', models.CharField(max_length=20, verbose_name='地区')),
                ('pschool', models.CharField(max_length=10, verbose_name='学校')),
                ('psch_code', models.CharField(max_length=4, verbose_name='学校代码')),
                ('pprofess_name', models.CharField(max_length=30, verbose_name='专业名称')),
                ('pprofess_code', models.CharField(max_length=3, verbose_name='专业代码')),
                ('psubject', models.CharField(max_length=20, null=True, verbose_name='学科要求')),
                ('premark', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('pplan_num', models.SmallIntegerField(null=True, verbose_name='计划数')),
                ('pscore_line', models.SmallIntegerField(null=True, verbose_name='分数线')),
                ('prank', models.IntegerField(null=True, verbose_name='位次')),
                ('plever', models.CharField(choices=[(1, '第一批'), (2, '第二批'), (3, '第三批')], max_length=3, verbose_name='层次')),
                ('pyear', models.CharField(max_length=4, verbose_name='年份')),
            ],
            options={
                'db_table': 'tb_profess',
            },
        ),
    ]
