# Generated by Django 3.2.3 on 2021-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0002_alter_professinformation_psubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professinformation',
            name='pprofess_name',
            field=models.CharField(max_length=100, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='professinformation',
            name='pschool',
            field=models.CharField(max_length=100, verbose_name='学校'),
        ),
    ]
