# Generated by Django 3.2.4 on 2021-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('passwoar', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=50, verbose_name='用户邮箱')),
                ('is_super', models.BooleanField(default='False', verbose_name='是否是管理员')),
            ],
        ),
    ]
