# Generated by Django 3.2.4 on 2021-06-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwoar',
            new_name='passwoad',
        ),
    ]
