# Generated by Django 3.2.4 on 2021-06-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_passwoar_user_passwoad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwoad',
            new_name='password',
        ),
    ]
